steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'asia-south1-docker.pkg.dev/tough-bindery-483312-t2/hotel-management/hotel-management-system:$BUILD_ID'
      - '-t'
      - 'asia-south1-docker.pkg.dev/tough-bindery-483312-t2/hotel-management/hotel-management-system:latest'
      - '.'
  
  # Push the Docker images
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - 'asia-south1-docker.pkg.dev/tough-bindery-483312-t2/hotel-management/hotel-management-system:$BUILD_ID'
  
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - 'asia-south1-docker.pkg.dev/tough-bindery-483312-t2/hotel-management/hotel-management-system:latest'

images:
  - 'asia-south1-docker.pkg.dev/tough-bindery-483312-t2/hotel-management/hotel-management-system:$BUILD_ID'
  - 'asia-south1-docker.pkg.dev/tough-bindery-483312-t2/hotel-management/hotel-management-system:latest'

timeout: '1200s'